class TodoException(Exception):
    pass


class TodoCompletedException(TodoException):
    pass
